---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
before_install: gem install bundler -v 1.17.3
script:
  - bin/style --config .rubocop.yml
  - bin/typecheck
  - bin/test
